# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'page_users',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='html_content',
        ),
        migrations.AddField(
            model_name='pageuser',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
        migrations.AddField(
            model_name='pageuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.User'),
        ),
    ]
