# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171124_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_message_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
