# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171124_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagechange',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.User'),
            preserve_default=False,
        ),
    ]
