# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagechange_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='github_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_avatar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_uid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
